version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - USER_SERVICE_URL=http://user-service:8081
      - FEED_SERVICE_URL=http://feed-service:8082
      - CONTENT_SERVICE_URL=http://content-service:8083
      - AUTH_SERVICE_URL=http://auth-service:8084
      - JWT_SECRET=your-secret-key-here
    depends_on:
      - user-service
      - feed-service
    networks:
      - pixelle-network

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - pixelle-network

  feed-service:
    build:
      context: .
      dockerfile: services/feed-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      - pixelle-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - pixelle-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pixelle
      - POSTGRES_USER=pixelle
      - POSTGRES_PASSWORD=pixelle123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pixelle-network

volumes:
  postgres_data:

networks:
  pixelle-network:
    driver: bridge
