[package]
name = "pixelle-chaos-monkey"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
clap = { workspace = true }
pixelle-core = { path = "../../crates/pixelle-core" }
anyhow = { workspace = true }
