# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

components:

  # ── Rust crates (crates.io) ────────────────────────────────────────────────
  rust-sdk:
    tag_pattern: "^messenger-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: crates
    package: messenger
    version_file: "core/sdk/Cargo.toml"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  rust-cli:
    tag_pattern: "^cli-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: crates
    package: messenger-cli
    version_file: "core/cli/Cargo.toml"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  rust-binary-protocol:
    tag_pattern: "^binary-protocol-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: crates
    package: messenger_binary_protocol
    version_file: "core/binary_protocol/Cargo.toml"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  rust-common:
    tag_pattern: "^common-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: crates
    package: messenger_common
    version_file: "core/common/Cargo.toml"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  # ── DockerHub images ───────────────────────────────────────────────────────
  rust-server:
    tag_pattern: "^server-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/messenger
    dockerfile: core/server/Dockerfile
    platforms: ["linux/amd64", "linux/arm64"]
    version_file: "core/server/Cargo.toml"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  rust-mcp:
    tag_pattern: "^mcp-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/messenger-mcp
    dockerfile: core/ai/mcp/Dockerfile
    platforms: ["linux/amd64", "linux/arm64"]
    version_file: "core/ai/mcp/Cargo.toml"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  rust-bench-dashboard:
    tag_pattern: "^bench-dashboard-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/messenger-bench-dashboard
    dockerfile: core/bench/dashboard/server/Dockerfile
    platforms: ["linux/amd64", "linux/arm64"]
    version_file: "core/bench/dashboard/server/Cargo.toml"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  rust-connectors:
    tag_pattern: "^connectors-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/messenger-connect
    dockerfile: core/connectors/runtime/Dockerfile
    platforms: ["linux/amd64", "linux/arm64"]
    version_file: "core/connectors/runtime/Cargo.toml"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  web-ui:
    tag_pattern: "^web-ui-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: dockerhub
    image: apache/messenger-web-ui
    dockerfile: web/Dockerfile
    platforms: ["linux/amd64", "linux/arm64"]
    version_file: "web/package.json"
    version_regex: '"version"\s*:\s*"([^"]+)"'

  # ── Other SDKs ─────────────────────────────────────────────────────────────
  sdk-python:
    tag_pattern: "^python-sdk-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: pypi
    version_file: "foreign/python/pyproject.toml"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  sdk-node:
    tag_pattern: "^node-sdk-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: npm
    version_file: "foreign/node/package.json"
    version_regex: '"version"\s*:\s*"([^"]+)"'

  sdk-java:
    tag_pattern: "^java-sdk-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: maven
    version_file: "foreign/java/java-sdk/build.gradle.kts"
    version_regex: '(?m)^\s*version\s*=\s*"([^"]+)"'

  sdk-csharp:
    tag_pattern: "^csharp-sdk-([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: nuget
    version_file: "foreign/csharp/Messenger_SDK/Messenger_SDK.csproj"
    version_regex: '(?ms)<(?:PackageVersion|Version)>\s*([^<]+)\s*</(?:PackageVersion|Version)>'

  # ── Go (tag only, no registry publish) ─────────────────────────────────────
  sdk-go:
    tag_pattern: "^foreign/go/v([0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?)$"
    registry: none
